title: Just the Docs Test
description: Test - A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://vijaya-lakshmi-venkatraman.github.io/just-the-docs

aux_links:
  "Edit on Github": https://github.com/vijaya-lakshmi-venkatraman/just-the-docs
